### PR TITLE
feat(lazyload-image): add class when an error loading image occurs

### PR DESCRIPTION
**Pull request by diogoqueiros24**

### CODE REVIEW

**Comment by tjoskar** [comment]
Hi @diogoqueiros24, 

Thanks, it looks nice. I think however we should change the error-class-name to `ng-failed-lazyloaded` instead of `ng2-failed-lazyloaded` since the library nowadays is called `ng-lazyload-image` (since angular 4 was released and the `2` in `ng2-lazyload-image` didn't make any sense any more). See: https://github.com/diogoqueiros24/ng-lazyload-image/blob/2bf681cfa91ad86d3a91b39cc683eb829d543e39/src/lazyload-image.ts#L60

**Comment by diogoqueiros24** [comment]
Hi @tjoskar .

Changed. :)

**Comment by tjoskar** [comment]
Thanks 🎉

**Comment by tjoskar** [comment]
Included in version 3.1.0

**Pull request merged**
